spring.profiles.active: prod

systemUser:
  age: 28
  web:
    name: web
  system:
    name: system

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sam47kon
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: create


database:
  dialect: h2sql
  url: postgresql://localhost:5432
  user: postgre
  password: 1234
  driver: PostgresDriver
  properties:
    dbName: myDb
    checkSQL: select 1
  pools:
    - poolSize: 10
      maxPoolSize: 30
      minPoolSize: 5
      idleTimeout: 7200
      maxIdleTime: 36000
    - poolSize: 5
      maxPoolSize: 10
      minPoolSize: 2
      idleTimeout: 900
      maxIdleTime: 6000

# logback
logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: info
#  file:
#    name: server.log
